- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.vst
  path: /
  secure: false
  value: F-NEglmTgiuZuAH3ArBQRuuHlNHyuwgtr-IO3ta0fcngebRYdxrZZ5la1kChA3HydoUyXJLh1uz6MTturE2gX8djPWtXMZFrTixj9QfDWXWPWAe2Hx_lw0Zc-WAsePPM09paPpAe0K8g0so04LxHTiZfyZAqifquXd4hpkRCW5SUmUKt_DSywaFKHscNyrl-BUlDwz4voyRZIsDRIlJPFmzWQocr63455T6G9iHbqA8s4sbU21X_EGpl-39ccqPTDT1nhTqg4nuWkl36GjB-UQ
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.logined
  path: /
  secure: false
  value: 'true'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.vid
  path: /
  secure: false
  value: '1688854284316806'
- domain: .qq.com
  httpOnly: false
  name: pgv_info
  path: /
  secure: true
  value: ssid=s5899838943
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.corpid
  path: /
  secure: false
  value: '1970326212982084'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.vid
  path: /
  secure: false
  value: '1688854284316806'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ltype
  path: /
  secure: false
  value: '1'
- domain: .qq.com
  httpOnly: false
  name: ptcz
  path: /
  secure: true
  value: a73e8e0a0113dc077b6e392cb3e68d92e38519ba2361f0b3f450db464e9ca91b
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.d2st
  path: /
  secure: false
  value: a8716628
- domain: .qq.com
  httpOnly: false
  name: RK
  path: /
  secure: true
  value: JZ0N8UpwRY
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ref
  path: /
  secure: true
  value: direct
- domain: .qq.com
  httpOnly: false
  name: eas_sid
  path: /
  secure: true
  value: q1f6y3U7j556O3N2B9p261w126
- domain: .qq.com
  httpOnly: false
  name: tvfe_boss_uuid
  path: /
  secure: true
  value: a2e99cf27f2ff77c
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.sid
  path: /
  secure: false
  value: u4YAMImbBA0_VM1QktMjgwaTR1LZMnOJD1hcsuoYnrPl3iCW9mX6JnXvmKkKbxWJ
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.cs_ind
  path: /
  secure: true
  value: ''
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.c_gdpr
  path: /
  secure: true
  value: '0'
- domain: .qq.com
  httpOnly: false
  name: pac_uid
  path: /
  secure: true
  value: 0_89d125b157d17
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.refid
  path: /
  secure: true
  value: '368645372627196'
- domain: .qq.com
  httpOnly: false
  name: pgv_pvid
  path: /
  secure: true
  value: '4368392512'
- domain: .qq.com
  httpOnly: false
  name: _ga
  path: /
  secure: true
  value: GA1.2.616229761.1636703823
- domain: .work.weixin.qq.com
  expiry: 1656729581
  httpOnly: false
  name: wwrtx.i18n_lan
  path: /
  secure: false
  value: zh
- domain: .work.weixin.qq.com
  httpOnly: false
  name: Hm_lvt_9364e629af24cb52acc78b43e8c9f77d
  path: /
  secure: true
  value: 1636703527,1636703542
