# NOTE: Generated By HttpRunner v3.1.11
# FROM: testcases\mubu_login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):

    config = Config("testcase description").base_url("https://api2.mubu.com/")\
        .verify(False)

    teststeps = [
        Step(
            RunRequest("/v3/api/user/phone_login")
            .post("/v3/api/user/phone_login")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "65",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "9d41b7f7-6c38-4a41-a197-bfd1a8154f85",
                }
            )
            .with_json(
                {"callbackType": 0, "password": "gxl10230701", "phone": "15222186256"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "12",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAzNjU3MiIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTY1NjIzMjgyNiwiaWF0IjoxNjUzNjQwODI2fQ.pAjYnbr7Lku5kzJ2Nr8dlZQx_V-2yO79frpxqSJcE-EznHQA5w3SXBYN6V2VqRXTz2UaMKCP9KTEocFe-Op-Kw",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "07ae2309-0b60-48bf-8718-cc6b49cd2c5c",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAzNjU3MiIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTY1NjIzMjgyNiwiaWF0IjoxNjUzNjQwODI2fQ.pAjYnbr7Lku5kzJ2Nr8dlZQx_V-2yO79frpxqSJcE-EznHQA5w3SXBYN6V2VqRXTz2UaMKCP9KTEocFe-Op-Kw",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "92aa82c8-d2e1-4992-aecc-b14156219467",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "0",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAzNjU3MiIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTY1NjIzMjgyNiwiaWF0IjoxNjUzNjQwODI2fQ.pAjYnbr7Lku5kzJ2Nr8dlZQx_V-2yO79frpxqSJcE-EznHQA5w3SXBYN6V2VqRXTz2UaMKCP9KTEocFe-Op-Kw",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "2e9348d0-d2c7-479d-a255-8c8499dbe070",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "10",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAzNjU3MiIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTY1NjIzMjgyNiwiaWF0IjoxNjUzNjQwODI2fQ.pAjYnbr7Lku5kzJ2Nr8dlZQx_V-2yO79frpxqSJcE-EznHQA5w3SXBYN6V2VqRXTz2UaMKCP9KTEocFe-Op-Kw",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "ad926491-a99c-4e2c-ba88-4a359cb4aedc",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_onboard_state")
            .post("/v3/api/user/get_onboard_state")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "2",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "99620c70-dd98-11ec-8003-35b78b1e9458",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAzNjU3MiIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTY1NjIzMjgyNiwiaWF0IjoxNjUzNjQwODI2fQ.pAjYnbr7Lku5kzJ2Nr8dlZQx_V-2yO79frpxqSJcE-EznHQA5w3SXBYN6V2VqRXTz2UaMKCP9KTEocFe-Op-Kw",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
                    "version": "3.0.0-2.0.0.1824",
                    "x-request-id": "5962168b-d1de-41c8-8e22-d58e02bddc23",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
